// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subscription.sql

package storage

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const calculateSubscriptionsTotal = `-- name: CalculateSubscriptionsTotal :one
SELECT COALESCE(SUM(
    price * (
        (
            EXTRACT(YEAR FROM AGE(
                LEAST(COALESCE(end_date, $1::date), $1::date),
                GREATEST(start_date, $2::date)
            ))::int * 12
        )
        + EXTRACT(MONTH FROM AGE(
            LEAST(COALESCE(end_date, $1::date), $1::date),
            GREATEST(start_date, $2::date)
        ))::int
        + 1
    )
), 0)::int
FROM subscriptions
WHERE
    user_id = $3
    AND service_name = $4
    AND start_date <= $1::date
    AND (end_date IS NULL OR end_date >= $2::date)
`

type CalculateSubscriptionsTotalParams struct {
	EndPeriod   pgtype.Date
	StartPeriod pgtype.Date
	UserID      uuid.UUID
	ServiceName string
}

func (q *Queries) CalculateSubscriptionsTotal(ctx context.Context, arg CalculateSubscriptionsTotalParams) (int32, error) {
	row := q.db.QueryRow(ctx, calculateSubscriptionsTotal,
		arg.EndPeriod,
		arg.StartPeriod,
		arg.UserID,
		arg.ServiceName,
	)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createSubscription = `-- name: CreateSubscription :one
INSERT INTO subscriptions (
    service_name,
    price,
    user_id,
    start_date,
    end_date
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, service_name, price, user_id, start_date, end_date
`

type CreateSubscriptionParams struct {
	ServiceName string
	Price       int32
	UserID      uuid.UUID
	StartDate   pgtype.Date
	EndDate     *time.Time
}

func (q *Queries) CreateSubscription(ctx context.Context, arg CreateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, createSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const deleteSubscription = `-- name: DeleteSubscription :execrows
DELETE
FROM subscriptions
WHERE id = $1
`

func (q *Queries) DeleteSubscription(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSubscription, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSubscriptionByID = `-- name: GetSubscriptionByID :one
SELECT id, service_name, price, user_id, start_date, end_date
FROM subscriptions
WHERE id = $1
`

func (q *Queries) GetSubscriptionByID(ctx context.Context, id uuid.UUID) (Subscription, error) {
	row := q.db.QueryRow(ctx, getSubscriptionByID, id)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}

const listSubscriptions = `-- name: ListSubscriptions :many
SELECT id, service_name, price, user_id, start_date, end_date
FROM subscriptions
WHERE user_id = $1
ORDER BY start_date DESC, service_name ASC
`

func (q *Queries) ListSubscriptions(ctx context.Context, userID uuid.UUID) ([]Subscription, error) {
	rows, err := q.db.Query(ctx, listSubscriptions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subscription
	for rows.Next() {
		var i Subscription
		if err := rows.Scan(
			&i.ID,
			&i.ServiceName,
			&i.Price,
			&i.UserID,
			&i.StartDate,
			&i.EndDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSubscription = `-- name: UpdateSubscription :one
UPDATE subscriptions
SET
    service_name = $1,
    price = $2,
    user_id = $3,
    start_date = $4,
    end_date = $5
WHERE id = $6
RETURNING id, service_name, price, user_id, start_date, end_date
`

type UpdateSubscriptionParams struct {
	ServiceName string
	Price       int32
	UserID      uuid.UUID
	StartDate   pgtype.Date
	EndDate     *time.Time
	ID          uuid.UUID
}

func (q *Queries) UpdateSubscription(ctx context.Context, arg UpdateSubscriptionParams) (Subscription, error) {
	row := q.db.QueryRow(ctx, updateSubscription,
		arg.ServiceName,
		arg.Price,
		arg.UserID,
		arg.StartDate,
		arg.EndDate,
		arg.ID,
	)
	var i Subscription
	err := row.Scan(
		&i.ID,
		&i.ServiceName,
		&i.Price,
		&i.UserID,
		&i.StartDate,
		&i.EndDate,
	)
	return i, err
}
