// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Error defines model for Error.
type Error struct {
	// Message Error Description
	Message string `json:"message"`
}

// Subscription defines model for Subscription.
type Subscription struct {
	// EndDate Date of subscription ending, optional
	//
	// Example: 12-2025
	EndDate *string            `json:"end_date,omitempty"`
	Id      openapi_types.UUID `json:"id"`

	// Price Price in rubles
	//
	// Example: 400
	Price int `json:"price"`

	// ServiceName Example: Yandex Plus
	ServiceName string `json:"service_name"`

	// StartDate Month and year of subscription start
	//
	// Example: 07-2025
	StartDate string `json:"start_date"`

	// UserId Example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
	UserId openapi_types.UUID `json:"user_id"`
}

// SubscriptionCreate defines model for SubscriptionCreate.
type SubscriptionCreate struct {
	// EndDate Example: 12-2025
	EndDate *string `json:"end_date,omitempty"`

	// Price Example: 400
	Price int `json:"price"`

	// ServiceName Example: Yandex Plus
	ServiceName string `json:"service_name"`

	// StartDate Example: 07-2025
	StartDate string `json:"start_date"`

	// UserId Example: 60601fee-2bf1-4721-ae6f-7636e79a0cba
	UserId openapi_types.UUID `json:"user_id"`
}

// TotalCostResponse defines model for TotalCostResponse.
type TotalCostResponse struct {
	// TotalCost Total cost in rubles
	//
	// Example: 1200
	TotalCost int `json:"total_cost"`
}

// BadRequest defines model for BadRequest.
type BadRequest = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ListSubscriptionsParams defines parameters for ListSubscriptions.
type ListSubscriptionsParams struct {
	// UserId User ID
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`
}

// CalculateTotalCostParams defines parameters for CalculateTotalCost.
type CalculateTotalCostParams struct {
	// UserId User ID
	UserId openapi_types.UUID `form:"user_id" json:"user_id"`

	// ServiceName Service name
	ServiceName string `form:"service_name" json:"service_name"`

	// StartPeriod Beginning of the period
	StartPeriod string `form:"start_period" json:"start_period"`

	// EndPeriod End of the period
	EndPeriod string `form:"end_period" json:"end_period"`
}

// CreateSubscriptionJSONRequestBody defines body for CreateSubscription for application/json ContentType.
type CreateSubscriptionJSONRequestBody = SubscriptionCreate

// UpdateSubscriptionJSONRequestBody defines body for UpdateSubscription for application/json ContentType.
type UpdateSubscriptionJSONRequestBody = SubscriptionCreate

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListSubscriptions Get a list of a user's subscriptions
	// (GET /subscriptions)
	ListSubscriptions(ctx echo.Context, params ListSubscriptionsParams) error
	// CreateSubscription Create a subscription entry
	// (POST /subscriptions)
	CreateSubscription(ctx echo.Context) error
	// CalculateTotalCost Calculating the total cost of subscriptions
	// (GET /subscriptions/cost)
	CalculateTotalCost(ctx echo.Context, params CalculateTotalCostParams) error
	// DeleteSubscription Delete subscription
	// (DELETE /subscriptions/{id})
	DeleteSubscription(ctx echo.Context, id openapi_types.UUID) error
	// GetSubscription Get a subscription by ID
	// (GET /subscriptions/{id})
	GetSubscription(ctx echo.Context, id openapi_types.UUID) error
	// UpdateSubscription Update subscription details
	// (PUT /subscriptions/{id})
	UpdateSubscription(ctx echo.Context, id openapi_types.UUID) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListSubscriptions converts echo context to params.
func (w *ServerInterfaceWrapper) ListSubscriptions(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListSubscriptionsParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", ctx.QueryParams(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSubscriptions(ctx, params)
	return err
}

// CreateSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSubscription(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSubscription(ctx)
	return err
}

// CalculateTotalCost converts echo context to params.
func (w *ServerInterfaceWrapper) CalculateTotalCost(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalculateTotalCostParams
	// ------------- Required query parameter "user_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "user_id", ctx.QueryParams(), &params.UserId, runtime.BindQueryParameterOptions{Type: "string", Format: "uuid"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter user_id: %s", err))
	}

	// ------------- Required query parameter "service_name" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "service_name", ctx.QueryParams(), &params.ServiceName, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter service_name: %s", err))
	}

	// ------------- Required query parameter "start_period" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "start_period", ctx.QueryParams(), &params.StartPeriod, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter start_period: %s", err))
	}

	// ------------- Required query parameter "end_period" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "end_period", ctx.QueryParams(), &params.EndPeriod, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter end_period: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalculateTotalCost(ctx, params)
	return err
}

// DeleteSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteSubscription(ctx, id)
	return err
}

// GetSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) GetSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSubscription(ctx, id)
	return err
}

// UpdateSubscription converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSubscription(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSubscription(ctx, id)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/subscriptions", wrapper.ListSubscriptions, options.OperationMiddlewares["listSubscriptions"]...)
	router.POST(options.BaseURL+"/subscriptions", wrapper.CreateSubscription, options.OperationMiddlewares["createSubscription"]...)
	router.DELETE(options.BaseURL+"/subscriptions/:id", wrapper.DeleteSubscription, options.OperationMiddlewares["deleteSubscription"]...)
	router.GET(options.BaseURL+"/subscriptions/:id", wrapper.GetSubscription, options.OperationMiddlewares["getSubscription"]...)
	router.PUT(options.BaseURL+"/subscriptions/:id", wrapper.UpdateSubscription, options.OperationMiddlewares["updateSubscription"]...)
	router.GET(options.BaseURL+"/subscriptions/cost", wrapper.CalculateTotalCost, options.OperationMiddlewares["calculateTotalCost"]...)

}

type BadRequestJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type ListSubscriptionsRequestObject struct {
	Params ListSubscriptionsParams
}

type ListSubscriptionsResponseObject interface {
	VisitListSubscriptionsResponse(w http.ResponseWriter) error
}

type ListSubscriptions200JSONResponse []Subscription

func (response ListSubscriptions200JSONResponse) VisitListSubscriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSubscriptions400JSONResponse struct{ BadRequestJSONResponse }

func (response ListSubscriptions400JSONResponse) VisitListSubscriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListSubscriptions500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListSubscriptions500JSONResponse) VisitListSubscriptionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubscriptionRequestObject struct {
	Body *CreateSubscriptionJSONRequestBody
}

type CreateSubscriptionResponseObject interface {
	VisitCreateSubscriptionResponse(w http.ResponseWriter) error
}

type CreateSubscription201JSONResponse Subscription

func (response CreateSubscription201JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubscription400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSubscription400JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSubscription500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSubscription500JSONResponse) VisitCreateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CalculateTotalCostRequestObject struct {
	Params CalculateTotalCostParams
}

type CalculateTotalCostResponseObject interface {
	VisitCalculateTotalCostResponse(w http.ResponseWriter) error
}

type CalculateTotalCost200JSONResponse TotalCostResponse

func (response CalculateTotalCost200JSONResponse) VisitCalculateTotalCostResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalculateTotalCost400JSONResponse struct{ BadRequestJSONResponse }

func (response CalculateTotalCost400JSONResponse) VisitCalculateTotalCostResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalculateTotalCost500JSONResponse struct{ InternalErrorJSONResponse }

func (response CalculateTotalCost500JSONResponse) VisitCalculateTotalCostResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSubscriptionRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteSubscriptionResponseObject interface {
	VisitDeleteSubscriptionResponse(w http.ResponseWriter) error
}

type DeleteSubscription204Response struct {
}

func (response DeleteSubscription204Response) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSubscription404JSONResponse) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSubscription500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSubscription500JSONResponse) VisitDeleteSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscriptionRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetSubscriptionResponseObject interface {
	VisitGetSubscriptionResponse(w http.ResponseWriter) error
}

type GetSubscription200JSONResponse Subscription

func (response GetSubscription200JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response GetSubscription404JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSubscription500JSONResponse struct{ InternalErrorJSONResponse }

func (response GetSubscription500JSONResponse) VisitGetSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSubscriptionRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateSubscriptionJSONRequestBody
}

type UpdateSubscriptionResponseObject interface {
	VisitUpdateSubscriptionResponse(w http.ResponseWriter) error
}

type UpdateSubscription200JSONResponse Subscription

func (response UpdateSubscription200JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSubscription400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSubscription400JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSubscription404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSubscription404JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSubscription500JSONResponse struct{ InternalErrorJSONResponse }

func (response UpdateSubscription500JSONResponse) VisitUpdateSubscriptionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// ListSubscriptions Get a list of a user's subscriptions
	// (GET /subscriptions)
	ListSubscriptions(ctx context.Context, request ListSubscriptionsRequestObject) (ListSubscriptionsResponseObject, error)
	// CreateSubscription Create a subscription entry
	// (POST /subscriptions)
	CreateSubscription(ctx context.Context, request CreateSubscriptionRequestObject) (CreateSubscriptionResponseObject, error)
	// CalculateTotalCost Calculating the total cost of subscriptions
	// (GET /subscriptions/cost)
	CalculateTotalCost(ctx context.Context, request CalculateTotalCostRequestObject) (CalculateTotalCostResponseObject, error)
	// DeleteSubscription Delete subscription
	// (DELETE /subscriptions/{id})
	DeleteSubscription(ctx context.Context, request DeleteSubscriptionRequestObject) (DeleteSubscriptionResponseObject, error)
	// GetSubscription Get a subscription by ID
	// (GET /subscriptions/{id})
	GetSubscription(ctx context.Context, request GetSubscriptionRequestObject) (GetSubscriptionResponseObject, error)
	// UpdateSubscription Update subscription details
	// (PUT /subscriptions/{id})
	UpdateSubscription(ctx context.Context, request UpdateSubscriptionRequestObject) (UpdateSubscriptionResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListSubscriptions operation middleware
func (sh *strictHandler) ListSubscriptions(ctx echo.Context, params ListSubscriptionsParams) error {
	var request ListSubscriptionsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListSubscriptions(ctx.Request().Context(), request.(ListSubscriptionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSubscriptions")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListSubscriptionsResponseObject); ok {
		return validResponse.VisitListSubscriptionsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSubscription operation middleware
func (sh *strictHandler) CreateSubscription(ctx echo.Context) error {
	var request CreateSubscriptionRequestObject

	var body CreateSubscriptionJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSubscription(ctx.Request().Context(), request.(CreateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSubscriptionResponseObject); ok {
		return validResponse.VisitCreateSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalculateTotalCost operation middleware
func (sh *strictHandler) CalculateTotalCost(ctx echo.Context, params CalculateTotalCostParams) error {
	var request CalculateTotalCostRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalculateTotalCost(ctx.Request().Context(), request.(CalculateTotalCostRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalculateTotalCost")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalculateTotalCostResponseObject); ok {
		return validResponse.VisitCalculateTotalCostResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteSubscription operation middleware
func (sh *strictHandler) DeleteSubscription(ctx echo.Context, id openapi_types.UUID) error {
	var request DeleteSubscriptionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSubscription(ctx.Request().Context(), request.(DeleteSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteSubscriptionResponseObject); ok {
		return validResponse.VisitDeleteSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSubscription operation middleware
func (sh *strictHandler) GetSubscription(ctx echo.Context, id openapi_types.UUID) error {
	var request GetSubscriptionRequestObject

	request.Id = id

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSubscription(ctx.Request().Context(), request.(GetSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSubscriptionResponseObject); ok {
		return validResponse.VisitGetSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateSubscription operation middleware
func (sh *strictHandler) UpdateSubscription(ctx echo.Context, id openapi_types.UUID) error {
	var request UpdateSubscriptionRequestObject

	request.Id = id

	var body UpdateSubscriptionJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSubscription(ctx.Request().Context(), request.(UpdateSubscriptionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSubscription")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateSubscriptionResponseObject); ok {
		return validResponse.VisitUpdateSubscriptionResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"zFhNb9s4EP0rBHeBvcix7KQJVrfNxxYBdosgaQ+LIghoceywoEllSGVrBPrvBUnZEiW57kdS52ZRI76Z",
	"NzNvJnmiuV4WWoGyhmZPFMEUWhnwD6eMX8NDCca6p1wrC8r/ZEUhRc6s0Gr8yWjlzkx+D0vmfv2OMKcZ",
	"/W3cXD0Ob834AlEjraoqoRxMjqJwl9DMYZE1WJXQS2UBFZPB/sXR13DkBvARkNSGCX2n7d+6VPzlXXin",
	"LQlQ7l1t7m7bUFCgLgCtCMlZgjFsAe5nfJG3J+ets4TaVQE0o8aiUAsPgPBQCgROs4+bq243hnr2CXKf",
	"iJty1rq86wQofseZHfDinFkgek5M63sCigu1SIj2j0zShMJntiykw5xMR9N0+oYmVJVSspk7tFhCz/uE",
	"Cp+PucYlszSjZSk4HTArUOQDrl25YyIUwXImwbSdOErTzT1CWViArwID+ChyuFNs6e9rnP6PKQ6fyZUs",
	"zZAHxjK0Wxj6Vyt7T5jiZAUMe1z5TyOC0pM1QT2c0gDeBVYa++P0OJ3MAUbT2XwyOjqZTkYMjuejk+PD",
	"Yzj5k6X5jNFkF42dWvEmER9rnhsvorh3FdUZQk3P9tL6oSLZZP8XZfeVJepnc/ReWybPtLHX9Ujop8g6",
	"k7tch/kQV7f/nLh3w502mQ4loxNDC6DvojMWaq772NcXN+9HdfxkrpG4oP8wRCspFMRtxpllhC0WCAu2",
	"FkthfVraVeoHg7vur6tLmtBHQBOwJgfpQer40gUoVgia0cOD9ODQUc7svedp3Eb0JwvwlDkyPeolpxn9",
	"Rxh7E1m6O5AtwQIamn3sxvnBAJLLc+p4oBl9KAFXrjN8Hbcy3VAaWqWZVLtK6jaJN4Jpmn7XJBQWlmbX",
	"SIxGTLVxgiGy1dCkdDx15dK4D4+Cd0NYmyjGraWmSuibb/kkXkb8eC6XS4YrmtG3YAkjsnaJrUut51tR",
	"d0mc8iB+EQEhXWDsqearZ1s7BhS3irvNlUbVS/fkRTwYymrUbabMczBmXkq5Irn3l+8rw4EuwrqrjMWV",
	"t4y7e7yWw7rF4yDPmMxLySwYYu+B2EYkXfFIGdeN1y5GDEjILXBSAArNEzIX0gICJ7OVrzdyee73iMjB",
	"Wvc79bbG36j7/jUm6UKupbaOYAi3M9y2g+8EO4WFUEqohcuAy0kgeRuun5kbk+24rWVgsmUZ6Ptyofg3",
	"eeFWo+/yodmanlvgv9bx/Q1ioO2bPWFv/V33hKuBflN2hLzf70+CV6HRJYRFMG65c3/ek/iI86O+UmyX",
	"wwBUy+HR7tg3f8I+B1khmogVd+/gPvMW7NfDTvczXNzKtx/2wrIQyfRs5dS12qHCkf8IuUbeEmW3aDbq",
	"8PMrX1EOZPNDwV/3qpK+glUFQcH/P7yq/PqCDEnt/EUElglpQuDG/z8slGSJkmZ0zAoxfpzQ6rb6EgAA",
	"//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
